name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  # Deploy PR Test Environment
  test:
    permissions:
      id-token: write
      contents: read
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/common.yaml
    with:
      workspace: pr-${{ github.event.pull_request.number }}
      backend_key: lambda/pr-${{ github.event.pull_request.number }}.tfstate
      dns_prefix: ${{ github.event.pull_request.number }}
      action: apply
    secrets: inherit

  # Destroy PR Test Environment after merge
  destroy-test:
    permissions:
      id-token: write
      contents: read
    if: github.event.pull_request.merged == true || github.event.pull_request.state == 'closed'
    needs: test
    uses: ./.github/workflows/common.yaml
    with:
      workspace: pr-${{ github.event.pull_request.number }}
      backend_key: lambda/pr-${{ github.event.pull_request.number }}.tfstate
      dns_prefix: ${{ github.event.pull_request.number }}
      action: destroy
    secrets: inherit

  # Deploy Production on Tag/Release
  production:
    permissions:
      id-token: write
      contents: read
    if: github.event_name == 'release'
    uses: ./.github/workflows/common.yaml
    with:
      workspace: prod
      backend_key: lambda/prod.tfstate
      dns_prefix: prod
      action: apply
    secrets: inherit

  # Destroy Production (manual only)
  destroy-production:
    permissions:
      id-token: write
      contents: read
    if: github.event_name == 'workflow_dispatch' && github.actor == github.repository_owner
    uses: ./.github/workflows/common.yaml
    with:
      workspace: prod
      backend_key: lambda/prod.tfstate
      dns_prefix: prod
      action: destroy
    secrets: inherit
